version: "3"
services:
    database:
        image: postgres:10.5
        restart: always
        environment:
            - POSTGRES_USER=dexter
            - POSTGRES_PASSWORD=dexter
            - POSTGRES_DB=dexter
            - PGDATA=/tmp
        volumes:
            - pgdata:/var/lib/postgresql/data/dbfiles
        ports:
            - '5432:5432'
    webserver:
        image: webdevops/apache:alpine
        depends_on:
            - php
        ports: 
            - "80:80"
            - "443:443"
        volumes: 
            - ".:/var/www/html"
        environment:
            WEB_PHP_SOCKET: "php:9000"
            WEB_PHP_TIMEOUT: 600
            WEB_DOCUMENT_ROOT: "/var/www/html"
    php:
        image: mlalbuquerque/php:7.1
        build:
            context: ./dockerfiles
            dockerfile: php7.1.dockerfile
        volumes:
            - ".:/var/www/html"
            - "./dockerfiles/config/php.ini:/usr/local/etc/php/php.ini"
            - "./dockerfiles/config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
        environment:
            PATH: "/root/.composer/vendor/bin:${PATH}"
volumes:
    pgdata: